### ISSUE TITLE
[BUG] 生成文档的时候，如果返回的值是泛型，生成的文档就会少这个字段

### ISSUE THREAD

**Issue by ExtremeYu** [gudqs7-idea-plugins/docer-savior-idea-plugin#81]
![image](https://user-images.githubusercontent.com/16620268/191399494-57bfa799-f566-457a-bbac-058473cd69ae.png)
![image](https://user-images.githubusercontent.com/16620268/191399538-2fff31a3-cbfb-4a2c-ac45-811df4c2e620.png)
![image](https://user-images.githubusercontent.com/16620268/191399571-b5850cff-fd31-41da-ba00-0d026f967cb2.png)

**Comment by ExtremeYu** [comment]
第一张图是class

**Comment by gudqs7** [comment]
@ExtremeYu  就是说少了应该有的第四层对吧?   我复现下试试, 看看啥情况

**Comment by gudqs7** [comment]
@ExtremeYu 发现问题了, 写去重时, key选错了导致的

**Comment by ExtremeYu** [comment]
哈哈哈，啥时候发板修复啊

**Comment by gudqs7** [comment]
@ExtremeYu 已经发了, 早上5点多也审核过了, 没收到更新的话, 从 release 那下载zip安装或者卸载后重新从商店下载, 更新机制这玩意咱控制不了, 延迟挺大的
