### ISSUE TITLE
 为什么生成的json解释后面会带一个数字？怎么控制不多显示这个

### ISSUE THREAD

**Issue by zhouyuanxing** [gudqs7-idea-plugins/docer-savior-idea-plugin#83]
![image](https://user-images.githubusercontent.com/27724043/191693695-d9afadbe-356e-4f55-9105-442bad60806e.png)
![image](https://user-images.githubusercontent.com/27724043/191693981-f77eb3d7-7de3-4ca4-8f8d-fc1c7ae2d010.png)

为什么生成的json解释后面会带一个数字？怎么控制不多显示这个

**Comment by gudqs7** [comment]
见 #79, 关掉随机生成就ok了

**Comment by zhouyuanxing** [comment]
![image](https://user-images.githubusercontent.com/27724043/191904932-0cd909c4-7888-4790-904b-7eb48e13f4a7.png)
生成的文档里面显示applicatin/json，应该是application/json少了个o

**Comment by gudqs7** [comment]
@zhouyuanxing 真细啊哥~  我改下 ftl 模版文件就好啦, 这个就不发版了, 我会在 commit 里关联这个issue
