### ISSUE TITLE
[BUG] 在生成较复杂接口时，响应部分的markdown最后一行未正确显示

### ISSUE THREAD

**Issue by ExtremeYu** [gudqs7-idea-plugins/docer-savior-idea-plugin#85]
![image](https://user-images.githubusercontent.com/16620268/192008967-b0ebc38c-66e8-44e5-bce7-21330feeb072.png)
如图，每一个层级最后一行都是###开头了

**Comment by gudqs7** [comment]
@ExtremeYu 老哥你进群了吗? 你这个我不好复现, 还有最好是能提供 markdown 内容, 光截图看不出原因
还有你换个 markdown 编辑器试试, 比如 GitHub 的

有个猜测, 是不是不太认识 标题4 啊, 或者和表格最后一行挨着导致的

**Comment by gudqs7** [comment]
@ExtremeYu 老哥你进群了吗? 你这个我不好复现, 还有最好是能提供 markdown 内容, 光截图看不出原因
还有你换个 markdown 编辑器试试, 比如 GitHub 的

有个猜测, 是不是不太认识 标题4 啊, 或者和表格最后一行挨着导致的

**Comment by gudqs7** [comment]
@ExtremeYu 老哥你进群了吗? 你这个我不好复现, 还有最好是能提供 markdown 内容, 光截图看不出原因
还有你换个 markdown 编辑器试试, 比如 GitHub 的

有个猜测, 是不是不太认识 标题4 啊, 或者和表格最后一行挨着导致的

**Comment by ExtremeYu** [comment]
哪个群啊

**Comment by ExtremeYu** [comment]
我都试了，就是那种返回值泛型套泛型、套泛型那种，群号发我下

**Comment by gudqs7** [comment]
钉钉群，置顶的issue里面有
发自我的iPhone

**Comment by ExtremeYu** [comment]
> 

https://github.com/docer-savior 这个点击去是404 

![image](https://user-images.githubusercontent.com/16620268/192149973-b3f164f4-1936-4c2c-873c-702c93344727.png)

**Comment by gudqs7** [comment]
@ExtremeYu 忘了改了...
https://github.com/gudqs7-idea-plugins
